package database

import (
	"go.uber.org/zap"
	"gorm.io/gorm"

	"tokenhub-server/internal/pkg/logger"
)

// RunExpandTrendingModels 扩充 trending_models 参考库。
// 依赖 ai_models.model_name 的 uniqueIndex 实现幂等：已存在的 model_name 会被 INSERT IGNORE 跳过。
// 数据来源（2026-04-21 WebSearch 交叉验证，见 docs/trending_models_expansion_review.md）：
//   - 只收录官方 API 列表 / GitHub 官方仓库 / 官网公告中确实存在的 model_id
//   - 不收录 "前瞻性命名" 和未发布的产品名
func RunExpandTrendingModels(db *gorm.DB) error {
	// model_name, display_name, supplier_name, launch_year_month, popularity_stars, model_type, description, source_url
	rows := [][]any{
		// ========== 1. DeepSeek（深度求索）==========
		{"deepseek-v3.2-exp", "DeepSeek V3.2 Exp", "DeepSeek", "2025-10", 4, "LLM", "V3.2 实验版，稀疏注意力 DSA", "https://api-docs.deepseek.com/"},
		{"deepseek-v3.1", "DeepSeek V3.1", "DeepSeek", "2025-08", 5, "LLM", "V3.1 首版，128K 上下文", "https://api-docs.deepseek.com/"},
		{"deepseek-v3", "DeepSeek V3 (671B)", "DeepSeek", "2024-12", 5, "LLM", "原版 V3，671B MoE 开源经典", "https://github.com/deepseek-ai/DeepSeek-V3"},
		{"deepseek-v3-base", "DeepSeek V3 Base", "DeepSeek", "2024-12", 3, "LLM", "V3 预训练基座（非对话）", "https://github.com/deepseek-ai/DeepSeek-V3"},
		{"deepseek-v2.5", "DeepSeek V2.5", "DeepSeek", "2024-09", 4, "LLM", "V2 系列末代融合版", "https://api-docs.deepseek.com/"},
		{"deepseek-v2-chat", "DeepSeek V2 Chat", "DeepSeek", "2024-05", 3, "LLM", "236B MoE 开源对话", "https://github.com/deepseek-ai/DeepSeek-V2"},
		{"deepseek-v2-lite", "DeepSeek V2 Lite (16B)", "DeepSeek", "2024-05", 3, "LLM", "轻量 16B MoE", "https://github.com/deepseek-ai/DeepSeek-V2"},
		{"deepseek-coder-v2", "DeepSeek Coder V2", "DeepSeek", "2024-06", 5, "Code", "代码 236B MoE，HumanEval SOTA", "https://github.com/deepseek-ai/DeepSeek-Coder-V2"},
		{"deepseek-coder-v2-lite", "DeepSeek Coder V2 Lite", "DeepSeek", "2024-06", 4, "Code", "16B 代码轻量版", "https://github.com/deepseek-ai/DeepSeek-Coder-V2"},
		{"deepseek-coder-33b-instruct", "DeepSeek Coder 33B", "DeepSeek", "2024-01", 3, "Code", "经典 33B 代码模型", "https://github.com/deepseek-ai/DeepSeek-Coder"},
		{"deepseek-math-7b-rl", "DeepSeek Math 7B", "DeepSeek", "2024-02", 3, "Reasoning", "数学推理专项", "https://github.com/deepseek-ai/DeepSeek-Math"},
		{"deepseek-r1", "DeepSeek R1（初代）", "DeepSeek", "2025-01", 5, "Reasoning", "引爆全球的原版 R1", "https://api-docs.deepseek.com/"},
		{"deepseek-r1-distill-qwen-32b", "R1-Distill-Qwen-32B", "DeepSeek", "2025-01", 4, "Reasoning", "R1 蒸馏 Qwen-32B", "https://github.com/deepseek-ai/DeepSeek-R1"},
		{"deepseek-r1-distill-qwen-14b", "R1-Distill-Qwen-14B", "DeepSeek", "2025-01", 3, "Reasoning", "R1 蒸馏 Qwen-14B", "https://github.com/deepseek-ai/DeepSeek-R1"},
		{"deepseek-r1-distill-llama-70b", "R1-Distill-Llama-70B", "DeepSeek", "2025-01", 4, "Reasoning", "R1 蒸馏 Llama-70B", "https://github.com/deepseek-ai/DeepSeek-R1"},
		{"deepseek-r1-distill-llama-8b", "R1-Distill-Llama-8B", "DeepSeek", "2025-01", 3, "Reasoning", "R1 蒸馏 Llama-8B", "https://github.com/deepseek-ai/DeepSeek-R1"},
		{"deepseek-vl2", "DeepSeek-VL2", "DeepSeek", "2024-12", 4, "VLM", "视觉多模态 MoE", "https://github.com/deepseek-ai/DeepSeek-VL2"},
		{"deepseek-vl2-small", "DeepSeek-VL2 Small", "DeepSeek", "2024-12", 3, "VLM", "视觉多模态轻量", "https://github.com/deepseek-ai/DeepSeek-VL2"},
		{"deepseek-prover-v2", "DeepSeek Prover V2", "DeepSeek", "2025-04", 3, "Reasoning", "形式化数学证明专项", "https://github.com/deepseek-ai/DeepSeek-Prover-V2"},

		// ========== 2. 阿里云 / Qwen ==========
		{"qwen3-max", "Qwen3-Max", "阿里云", "2026-01", 5, "Reasoning", "Qwen3 系列最强旗舰，2T MoE", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen3-max-2026-01-23", "Qwen3-Max 2026-01-23 快照", "阿里云", "2026-01", 4, "Reasoning", "qwen3-max 稳定版快照", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen3-vl-plus", "Qwen3-VL-Plus", "阿里云", "2025-09", 5, "VLM", "Qwen3 视觉旗舰", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen3-vl-flash", "Qwen3-VL-Flash", "阿里云", "2026-01", 4, "VLM", "Qwen3 视觉极速版", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen3-coder-plus", "Qwen3-Coder-Plus", "阿里云", "2025-07", 5, "Code", "Qwen3 代码旗舰", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen3-coder-flash", "Qwen3-Coder-Flash", "阿里云", "2025-07", 4, "Code", "Qwen3 代码极速版", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen3-coder-next", "Qwen3-Coder-Next", "阿里云", "2026-01", 4, "Code", "Qwen3 代码 Next 架构", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen3-omni-flash", "Qwen3-Omni Flash", "阿里云", "2025-09", 4, "VLM", "Qwen3 全模态（文本/图像/音频/视频）", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen3-next-80b-a3b", "Qwen3-Next 80B-A3B", "阿里云", "2025-09", 4, "LLM", "新架构开源预览", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen-max", "通义千问 Max", "阿里云", "2024-06", 4, "LLM", "经典商业旗舰", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen-max-latest", "Qwen Max Latest", "阿里云", "2025-09", 4, "LLM", "Max 最新快照", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen-plus", "通义千问 Plus", "阿里云", "2024-06", 5, "LLM", "商用均衡版，调用量最大", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen-plus-latest", "Qwen Plus Latest", "阿里云", "2025-09", 5, "LLM", "Plus 最新快照", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen-turbo", "通义千问 Turbo", "阿里云", "2024-06", 4, "LLM", "极速版", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen-turbo-latest", "Qwen Turbo Latest", "阿里云", "2025-09", 4, "LLM", "Turbo 最新快照", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen3-32b", "Qwen3-32B", "阿里云", "2025-04", 4, "LLM", "Qwen3 稠密 32B 开源", "https://github.com/QwenLM/Qwen3"},
		{"qwen3-14b", "Qwen3-14B", "阿里云", "2025-04", 3, "LLM", "Qwen3 稠密 14B", "https://github.com/QwenLM/Qwen3"},
		{"qwen3-8b", "Qwen3-8B", "阿里云", "2025-04", 3, "LLM", "Qwen3 稠密 8B", "https://github.com/QwenLM/Qwen3"},
		{"qwen3-4b", "Qwen3-4B", "阿里云", "2025-04", 3, "LLM", "Qwen3 稠密 4B", "https://github.com/QwenLM/Qwen3"},
		{"qwen3-1.7b", "Qwen3-1.7B", "阿里云", "2025-04", 2, "LLM", "Qwen3 稠密 1.7B", "https://github.com/QwenLM/Qwen3"},
		{"qwen3-0.6b", "Qwen3-0.6B", "阿里云", "2025-04", 2, "LLM", "Qwen3 稠密 0.6B", "https://github.com/QwenLM/Qwen3"},
		{"qwen3-30b-a3b", "Qwen3-30B-A3B", "阿里云", "2025-04", 4, "LLM", "Qwen3 MoE 30B/3B 激活", "https://github.com/QwenLM/Qwen3"},
		{"qwq-32b", "QwQ-32B（开源）", "阿里云", "2025-03", 4, "Reasoning", "Qwen 推理开源版", "https://github.com/QwenLM/QwQ"},
		{"qwq-32b-preview", "QwQ-32B-Preview", "阿里云", "2024-11", 3, "Reasoning", "QwQ 早期预览版", "https://github.com/QwenLM/QwQ"},
		{"qvq-72b-preview", "QvQ-72B-Preview", "阿里云", "2024-12", 3, "VLM", "视觉推理预览版", "https://github.com/QwenLM/QVQ"},
		{"qwen-vl-max", "Qwen-VL-Max", "阿里云", "2024-08", 4, "VLM", "视觉商用旗舰", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen-vl-plus", "Qwen-VL-Plus", "阿里云", "2024-08", 3, "VLM", "视觉均衡版", "https://help.aliyun.com/zh/model-studio/"},
		{"qwen2.5-72b-instruct", "Qwen2.5-72B", "阿里云", "2024-09", 4, "LLM", "Qwen2.5 旗舰开源", "https://github.com/QwenLM/Qwen2.5"},
		{"qwen2.5-coder-32b-instruct", "Qwen2.5-Coder-32B", "阿里云", "2024-11", 4, "Code", "Qwen2.5 代码旗舰", "https://github.com/QwenLM/Qwen2.5-Coder"},
		{"qwen2.5-math-72b-instruct", "Qwen2.5-Math-72B", "阿里云", "2024-09", 3, "Reasoning", "Qwen2.5 数学专项", "https://github.com/QwenLM/Qwen2.5-Math"},
		{"text-embedding-v3", "Qwen Embedding V3", "阿里云", "2024-06", 4, "Embedding", "阿里云通用 Embedding", "https://help.aliyun.com/zh/model-studio/"},
		{"gte-rerank", "GTE Rerank", "阿里云", "2024-08", 3, "Rerank", "阿里达摩院 Rerank", "https://help.aliyun.com/zh/model-studio/"},
		{"cosyvoice-v2", "CosyVoice V2", "阿里云", "2025-01", 4, "TTS", "通义语音合成", "https://help.aliyun.com/zh/model-studio/"},
		{"paraformer-v2", "Paraformer V2", "阿里云", "2024-12", 3, "ASR", "通义语音识别", "https://help.aliyun.com/zh/model-studio/"},
		{"wanx-v2.1", "通义万相 2.1", "阿里云", "2025-03", 4, "ImageGen", "阿里图像生成", "https://help.aliyun.com/zh/model-studio/"},

		// ========== 3. 火山引擎 / Doubao ==========
		{"doubao-seed-1.6", "豆包 Seed 1.6", "火山引擎", "2025-06", 5, "Reasoning", "Seed 1.6 推理旗舰", "https://www.volcengine.com/docs/82379"},
		{"doubao-seed-1.6-vision", "豆包 Seed 1.6 Vision", "火山引擎", "2025-08", 5, "VLM", "Seed 1.6 视觉版", "https://www.volcengine.com/docs/82379"},
		{"doubao-seed-1.6-flash", "豆包 Seed 1.6 Flash", "火山引擎", "2025-06", 4, "LLM", "Seed 1.6 极速版", "https://www.volcengine.com/docs/82379"},
		{"doubao-seed-1.6-thinking", "豆包 Seed 1.6 Thinking", "火山引擎", "2025-06", 5, "Reasoning", "Seed 1.6 深度思考", "https://www.volcengine.com/docs/82379"},
		{"doubao-seed-code", "豆包 Seed Code", "火山引擎", "2025-10", 4, "Code", "Seed 代码专项", "https://www.volcengine.com/docs/82379"},
		{"doubao-seedance-1.5-pro", "Seedance 1.5 Pro", "火山引擎", "2025-10", 5, "VideoGen", "Seedance 1.5 专业版视频生成", "https://www.volcengine.com/docs/82379"},
		{"doubao-pro-256k", "豆包 Pro 256K", "火山引擎", "2024-09", 4, "LLM", "经典 Pro 长上下文", "https://www.volcengine.com/docs/82379"},
		{"doubao-pro-128k", "豆包 Pro 128K", "火山引擎", "2024-05", 4, "LLM", "经典 Pro 128K", "https://www.volcengine.com/docs/82379"},
		{"doubao-pro-32k", "豆包 Pro 32K", "火山引擎", "2024-05", 3, "LLM", "经典 Pro 32K", "https://www.volcengine.com/docs/82379"},
		{"doubao-lite-128k", "豆包 Lite 128K", "火山引擎", "2024-05", 3, "LLM", "经典 Lite 长上下文", "https://www.volcengine.com/docs/82379"},
		{"doubao-lite-32k", "豆包 Lite 32K", "火山引擎", "2024-05", 3, "LLM", "经典 Lite 极速", "https://www.volcengine.com/docs/82379"},
		{"doubao-1.5-pro-32k", "豆包 1.5 Pro 32K", "火山引擎", "2025-01", 4, "LLM", "1.5 标准版", "https://www.volcengine.com/docs/82379"},
		{"doubao-1.5-lite", "豆包 1.5 Lite", "火山引擎", "2025-01", 3, "LLM", "1.5 极速版", "https://www.volcengine.com/docs/82379"},
		{"doubao-1.5-vision-pro", "豆包 1.5 Vision Pro", "火山引擎", "2025-01", 4, "VLM", "1.5 视觉旗舰", "https://www.volcengine.com/docs/82379"},
		{"doubao-1.5-vision-lite", "豆包 1.5 Vision Lite", "火山引擎", "2025-01", 3, "VLM", "1.5 视觉轻量", "https://www.volcengine.com/docs/82379"},
		{"doubao-vision-pro-32k", "豆包 Vision Pro", "火山引擎", "2024-10", 3, "VLM", "视觉经典版", "https://www.volcengine.com/docs/82379"},
		{"doubao-character", "豆包角色扮演", "火山引擎", "2024-08", 3, "LLM", "角色对话专项", "https://www.volcengine.com/docs/82379"},
		{"doubao-embedding", "豆包 Embedding", "火山引擎", "2024-08", 4, "Embedding", "字节通用 Embedding", "https://www.volcengine.com/docs/82379"},
		{"doubao-embedding-large", "豆包 Embedding Large", "火山引擎", "2025-02", 3, "Embedding", "字节大向量", "https://www.volcengine.com/docs/82379"},
		{"doubao-embedding-vision", "豆包 Embedding Vision-Text", "火山引擎", "2025-04", 3, "Embedding", "跨模态向量", "https://www.volcengine.com/docs/82379"},
		{"seedance-1.0-pro", "Seedance 1.0 Pro", "火山引擎", "2025-07", 4, "VideoGen", "Seedance 初代 Pro", "https://www.volcengine.com/docs/82379"},
		{"seedream-3.0", "Seedream 3.0", "火山引擎", "2025-04", 4, "ImageGen", "Seedream 经典版", "https://www.volcengine.com/docs/82379"},
		{"seedream-4.5", "Seedream 4.5", "火山引擎", "2025-12", 4, "ImageGen", "Seedream 4.5", "https://www.volcengine.com/docs/82379"},
		{"seed-tts-2.0", "豆包语音合成 2.0", "火山引擎", "2025-08", 3, "TTS", "Seed TTS 新版", "https://www.volcengine.com/docs/82379"},
		{"seed-asr-2.0", "豆包流式 ASR 2.0", "火山引擎", "2025-08", 3, "ASR", "Seed ASR 新版", "https://www.volcengine.com/docs/82379"},

		// ========== 4. 腾讯 Hunyuan ==========
		{"hunyuan-turbos", "混元 Turbo S", "腾讯", "2025-10", 5, "LLM", "Turbo S 最新旗舰", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-turbos-latest", "混元 Turbo S Latest", "腾讯", "2025-10", 5, "LLM", "Turbo S 最新快照", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-t1", "混元 T1", "腾讯", "2025-06", 5, "Reasoning", "T1 推理旗舰", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-t1-latest", "混元 T1 Latest", "腾讯", "2025-10", 5, "Reasoning", "T1 最新推理", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-t1-vision", "混元 T1 Vision", "腾讯", "2025-06", 4, "VLM", "T1 视觉推理", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-voice", "混元语音", "腾讯", "2025-09", 4, "TTS", "混元端到端语音", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-image-3.0-instruct", "混元图像 3.0 Instruct", "腾讯", "2026-01", 5, "ImageGen", "80B MoE 开源文生图", "https://github.com/Tencent-Hunyuan/HunyuanImage-3"},
		{"hunyuan-turbo", "混元 Turbo（经典）", "腾讯", "2024-11", 4, "LLM", "初代 Turbo", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-pro", "混元 Pro", "腾讯", "2024-05", 3, "LLM", "商用专业版", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-standard", "混元 Standard", "腾讯", "2024-05", 3, "LLM", "商用标准版", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-standard-256k", "混元 Standard 256K", "腾讯", "2024-07", 3, "LLM", "长上下文标准版", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-lite", "混元 Lite（免费）", "腾讯", "2024-05", 3, "LLM", "免费入门", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-code", "混元 Code", "腾讯", "2024-08", 4, "Code", "代码专项", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-role", "混元 Role", "腾讯", "2024-08", 3, "LLM", "角色扮演", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-functioncall", "混元 FunctionCall", "腾讯", "2024-09", 3, "LLM", "函数调用专项", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-vision", "混元 Vision（经典）", "腾讯", "2024-09", 3, "VLM", "初代视觉版", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-large-vision", "混元 Large Vision", "腾讯", "2025-03", 3, "VLM", "Large 视觉版", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-embedding", "混元 Embedding", "腾讯", "2024-10", 3, "Embedding", "腾讯向量化", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-translation", "混元翻译", "腾讯", "2024-12", 3, "LLM", "多语言翻译专项", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-a13b", "混元 A13B（开源）", "腾讯", "2025-06", 4, "LLM", "80B/13B MoE 开源", "https://github.com/Tencent-Hunyuan"},
		{"hunyuan-7b-instruct", "混元 7B Instruct", "腾讯", "2025-03", 3, "LLM", "7B 开源", "https://github.com/Tencent-Hunyuan"},
		{"hunyuan-dit", "混元 DiT（图像）", "腾讯", "2024-05", 4, "ImageGen", "腾讯首款 DiT 文生图", "https://github.com/Tencent-Hunyuan/HunyuanDiT"},
		{"hunyuan-image-2.1", "混元图像 2.1", "腾讯", "2025-09", 4, "ImageGen", "新一代文生图", "https://cloud.tencent.com/document/product/1729"},
		{"hunyuan-video", "混元视频生成", "腾讯", "2024-12", 4, "VideoGen", "腾讯视频生成开源", "https://github.com/Tencent-Hunyuan/HunyuanVideo"},

		// ========== 5. 百度 ERNIE ==========
		{"ernie-5.0", "文心 ERNIE 5.0", "百度", "2026-01", 5, "VLM", "5.0 正式版，2.4T 原生全模态", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-x1-turbo", "文心 ERNIE X1 Turbo", "百度", "2025-11", 5, "Reasoning", "X1 极速推理版", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-4.0-turbo-8k", "文心 4.0 Turbo 8K", "百度", "2024-06", 4, "LLM", "4.0 Turbo 经典", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-4.0-turbo-128k", "文心 4.0 Turbo 128K", "百度", "2024-08", 3, "LLM", "4.0 Turbo 长文本", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-4.0-8k", "文心 4.0", "百度", "2023-10", 3, "LLM", "初代 4.0", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-4.0-8k-latest", "ERNIE 4.0 Latest", "百度", "2024-12", 3, "LLM", "4.0 最新快照", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-3.5-8k", "文心 3.5", "百度", "2023-06", 3, "LLM", "3.5 经典", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-3.5-128k", "文心 3.5 128K", "百度", "2024-03", 3, "LLM", "3.5 长上下文", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-speed-8k", "ERNIE Speed", "百度", "2024-03", 3, "LLM", "极速推理", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-speed-128k", "ERNIE Speed 128K", "百度", "2024-05", 3, "LLM", "极速长上下文", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-speed-pro-128k", "ERNIE Speed Pro", "百度", "2024-09", 3, "LLM", "Speed 专业版", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-lite-8k", "ERNIE Lite", "百度", "2024-03", 3, "LLM", "轻量免费", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-lite-pro-128k", "ERNIE Lite Pro", "百度", "2024-09", 3, "LLM", "Lite 专业版", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-tiny-8k", "ERNIE Tiny", "百度", "2024-03", 2, "LLM", "极小模型", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-character-8k", "ERNIE Character", "百度", "2024-07", 3, "LLM", "角色扮演专项", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-functions-8k", "ERNIE Functions", "百度", "2024-07", 3, "LLM", "函数调用专项", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-novel-8k", "ERNIE Novel", "百度", "2024-08", 2, "LLM", "小说创作专项", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-4.5-turbo-vl-32k", "ERNIE 4.5 Turbo VL", "百度", "2025-05", 4, "VLM", "4.5 Turbo 视觉", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-4.5-8k-latest", "ERNIE 4.5 Latest", "百度", "2025-06", 4, "VLM", "4.5 最新快照", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-x1-32k-preview", "ERNIE X1 Preview", "百度", "2025-03", 3, "Reasoning", "X1 预览版", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"ernie-x1-pro-32k", "ERNIE X1 Pro", "百度", "2025-06", 4, "Reasoning", "X1 专业推理版", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"bge-large-zh", "BGE Large ZH", "百度", "2023-08", 4, "Embedding", "百度 BGE 中文向量", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"bge-reranker-large", "BGE Reranker Large", "百度", "2024-01", 3, "Rerank", "百度 BGE Rerank", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"embedding-v1", "百度通用 Embedding V1", "百度", "2024-03", 3, "Embedding", "千帆通用向量", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"tao-8k", "Tao-8K（Embedding）", "百度", "2024-05", 2, "Embedding", "长文本向量", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},
		{"irag", "iRAG（图像生成）", "百度", "2025-01", 3, "ImageGen", "百度文生图", "https://cloud.baidu.com/doc/WENXINWORKSHOP"},

		// ========== 6. Moonshot Kimi ==========
		{"kimi-k2.5", "Kimi K2.5", "Moonshot", "2026-01", 5, "LLM", "K2.5 开源 1T MoE / 32B 激活", "https://platform.moonshot.cn/docs"},
		{"kimi-k2.5-thinking", "Kimi K2.5 Thinking", "Moonshot", "2026-02", 5, "Reasoning", "K2.5 深度思考模式", "https://platform.moonshot.cn/docs"},
		{"kimi-k2.6-code-preview", "Kimi K2.6 Code Preview", "Moonshot", "2026-04", 5, "Code", "K2.6 代码预览（2026-04-13 发布）", "https://platform.moonshot.cn/docs"},
		{"moonshot-v1-8k", "Moonshot V1 8K", "Moonshot", "2024-03", 3, "LLM", "V1 短上下文", "https://platform.moonshot.cn/docs"},
		{"moonshot-v1-32k", "Moonshot V1 32K", "Moonshot", "2024-03", 4, "LLM", "V1 中等上下文", "https://platform.moonshot.cn/docs"},
		{"moonshot-v1-auto", "Moonshot V1 Auto", "Moonshot", "2024-10", 4, "LLM", "自动选择上下文", "https://platform.moonshot.cn/docs"},
		{"moonshot-v1-8k-vision-preview", "Moonshot V1 Vision 8K", "Moonshot", "2025-01", 3, "VLM", "V1 视觉预览", "https://platform.moonshot.cn/docs"},
		{"moonshot-v1-32k-vision-preview", "Moonshot V1 Vision 32K", "Moonshot", "2025-01", 3, "VLM", "V1 视觉 32K", "https://platform.moonshot.cn/docs"},
		{"moonshot-v1-128k-vision-preview", "Moonshot V1 Vision 128K", "Moonshot", "2025-01", 4, "VLM", "V1 视觉长上下文", "https://platform.moonshot.cn/docs"},
		{"kimi-latest", "Kimi Latest", "Moonshot", "2025-03", 4, "LLM", "自动路由最新版", "https://platform.moonshot.cn/docs"},
		{"kimi-latest-8k", "Kimi Latest 8K", "Moonshot", "2025-03", 3, "LLM", "Latest 8K", "https://platform.moonshot.cn/docs"},
		{"kimi-latest-32k", "Kimi Latest 32K", "Moonshot", "2025-03", 3, "LLM", "Latest 32K", "https://platform.moonshot.cn/docs"},
		{"kimi-latest-128k", "Kimi Latest 128K", "Moonshot", "2025-03", 4, "LLM", "Latest 128K", "https://platform.moonshot.cn/docs"},
		{"kimi-thinking-preview", "Kimi Thinking Preview", "Moonshot", "2025-05", 4, "Reasoning", "Thinking 预览", "https://platform.moonshot.cn/docs"},
		{"kimi-k2", "Kimi K2", "Moonshot", "2025-07", 5, "LLM", "K2 主入口", "https://platform.moonshot.cn/docs"},
		{"kimi-k2-instruct", "Kimi K2 Instruct", "Moonshot", "2025-09", 4, "LLM", "K2 指令版", "https://platform.moonshot.cn/docs"},
		{"kimi-k2-turbo-preview", "Kimi K2 Turbo", "Moonshot", "2025-11", 4, "LLM", "K2 极速版", "https://platform.moonshot.cn/docs"},
		{"kimi-audio-7b-instruct", "Kimi Audio 7B", "Moonshot", "2025-04", 3, "LLM", "Kimi 音频理解", "https://platform.moonshot.cn/docs"},
		{"moonshot-embedding-v1", "Moonshot Embedding V1", "Moonshot", "2025-02", 3, "Embedding", "Kimi 向量", "https://platform.moonshot.cn/docs"},

		// ========== 7. 智谱 GLM ==========
		{"glm-5", "GLM-5", "智谱", "2026-02", 5, "LLM", "GLM-5 开源 744B MoE 旗舰", "https://github.com/THUDM/GLM"},
		{"glm-5.1", "GLM-5.1", "智谱", "2026-03", 5, "LLM", "GLM-5.1 升级版", "https://open.bigmodel.cn/dev/api"},
		{"glm-5v-turbo", "GLM-5V Turbo", "智谱", "2026-04", 5, "VLM", "GLM-5 视觉 Turbo 版", "https://open.bigmodel.cn/dev/api"},
		{"glm-4.7-flash", "GLM-4.7 Flash", "智谱", "2026-03", 4, "LLM", "4.7 极速免费版", "https://open.bigmodel.cn/dev/api"},
		{"glm-4-0520", "GLM-4-0520", "智谱", "2024-05", 3, "LLM", "GLM-4 经典快照", "https://open.bigmodel.cn/dev/api"},
		{"glm-4-air", "GLM-4 Air", "智谱", "2024-05", 4, "LLM", "均衡商用", "https://open.bigmodel.cn/dev/api"},
		{"glm-4-airx", "GLM-4 AirX", "智谱", "2024-06", 3, "LLM", "Air 极速版", "https://open.bigmodel.cn/dev/api"},
		{"glm-4-long", "GLM-4 Long", "智谱", "2024-08", 3, "LLM", "长文本 1M Token", "https://open.bigmodel.cn/dev/api"},
		{"glm-4-9b-chat", "GLM-4-9B Chat", "智谱", "2024-06", 3, "LLM", "9B 开源对话", "https://github.com/THUDM/GLM-4"},
		{"glm-4v", "GLM-4V", "智谱", "2024-04", 3, "VLM", "首版视觉", "https://open.bigmodel.cn/dev/api"},
		{"glm-4v-plus", "GLM-4V Plus", "智谱", "2024-08", 4, "VLM", "视觉商用旗舰", "https://open.bigmodel.cn/dev/api"},
		{"glm-4v-flash", "GLM-4V Flash（免费）", "智谱", "2024-12", 3, "VLM", "视觉免费版", "https://open.bigmodel.cn/dev/api"},
		{"glm-4.5-air", "GLM-4.5 Air", "智谱", "2025-07", 3, "LLM", "4.5 轻量版", "https://open.bigmodel.cn/dev/api"},
		{"glm-4.5-flash", "GLM-4.5 Flash", "智谱", "2025-07", 3, "LLM", "4.5 极速版", "https://open.bigmodel.cn/dev/api"},
		{"glm-4.5v", "GLM-4.5V", "智谱", "2025-08", 4, "VLM", "4.5 视觉版", "https://open.bigmodel.cn/dev/api"},
		{"glm-4.6-air", "GLM-4.6 Air", "智谱", "2025-09", 3, "LLM", "4.6 轻量", "https://open.bigmodel.cn/dev/api"},
		{"glm-zero-preview", "GLM-Zero Preview", "智谱", "2025-01", 4, "Reasoning", "GLM-Zero 推理预览", "https://open.bigmodel.cn/dev/api"},
		{"codegeex-4", "CodeGeeX-4", "智谱", "2024-07", 4, "Code", "智谱代码专项", "https://github.com/THUDM/CodeGeeX4"},
		{"codegeex-4-all-9b", "CodeGeeX-4 All 9B", "智谱", "2024-07", 3, "Code", "代码开源", "https://github.com/THUDM/CodeGeeX4"},
		{"emohaa", "Emohaa（心理咨询）", "智谱", "2024-11", 2, "LLM", "共情对话专项", "https://open.bigmodel.cn/dev/api"},
		{"charglm-4", "CharGLM-4", "智谱", "2024-10", 3, "LLM", "角色扮演", "https://open.bigmodel.cn/dev/api"},
		{"embedding-3", "GLM Embedding-3", "智谱", "2024-08", 4, "Embedding", "智谱通用向量", "https://open.bigmodel.cn/dev/api"},
		{"embedding-2", "GLM Embedding-2", "智谱", "2024-05", 3, "Embedding", "旧版向量", "https://open.bigmodel.cn/dev/api"},
		{"cogview-3-plus", "CogView-3 Plus", "智谱", "2024-06", 3, "ImageGen", "智谱文生图", "https://open.bigmodel.cn/dev/api"},
		{"cogview-4", "CogView-4", "智谱", "2025-02", 4, "ImageGen", "智谱 DiT 文生图", "https://open.bigmodel.cn/dev/api"},

		// ========== 8. MiniMax ==========
		{"minimax-m2.7", "MiniMax M2.7", "MiniMax", "2026-03", 5, "Reasoning", "M2.7 旗舰（含推理模式）", "https://api.minimaxi.com/"},
		{"minimax-m2.5", "MiniMax M2.5", "MiniMax", "2026-01", 4, "LLM", "M2.5 上一代旗舰", "https://api.minimaxi.com/"},
		{"minimax-hailuo-2.5", "海螺 Hailuo 2.5", "MiniMax", "2026-03", 5, "VideoGen", "海螺 2.5 视频生成", "https://api.minimaxi.com/"},
		{"abab6.5s-chat", "abab 6.5s Chat", "MiniMax", "2024-04", 3, "LLM", "abab 极速版", "https://api.minimaxi.com/"},
		{"abab6.5-chat", "abab 6.5 Chat", "MiniMax", "2024-04", 3, "LLM", "abab 标准版", "https://api.minimaxi.com/"},
		{"abab6.5t-chat", "abab 6.5t Chat", "MiniMax", "2024-08", 3, "LLM", "abab turbo", "https://api.minimaxi.com/"},
		{"abab7-chat-preview", "abab 7 Chat Preview", "MiniMax", "2024-11", 3, "LLM", "abab 7 预览", "https://api.minimaxi.com/"},
		{"minimax-text-01", "MiniMax Text-01", "MiniMax", "2025-01", 4, "LLM", "闪电注意力 456B MoE", "https://api.minimaxi.com/"},
		{"minimax-vl-01", "MiniMax VL-01", "MiniMax", "2025-01", 3, "VLM", "多模态 Text-01", "https://api.minimaxi.com/"},
		{"minimax-m1-40k", "MiniMax M1 40K", "MiniMax", "2025-05", 4, "Reasoning", "M1 40K 思维链", "https://api.minimaxi.com/"},
		{"minimax-m1-80k", "MiniMax M1 80K", "MiniMax", "2025-05", 4, "Reasoning", "M1 80K 思维链", "https://api.minimaxi.com/"},
		{"minimax-hailuo-02", "海螺视频 02", "MiniMax", "2025-06", 4, "VideoGen", "海螺 02", "https://api.minimaxi.com/"},
		{"minimax-hailuo-2.2", "海螺 Hailuo 2.2", "MiniMax", "2025-08", 3, "VideoGen", "海螺 2.2", "https://api.minimaxi.com/"},
		{"minimax-speech-01-turbo", "Speech-01 Turbo", "MiniMax", "2025-01", 3, "TTS", "极速语音合成", "https://api.minimaxi.com/"},
		{"minimax-speech-01-hd", "Speech-01 HD", "MiniMax", "2025-01", 3, "TTS", "高保真语音", "https://api.minimaxi.com/"},
		{"minimax-speech-02-hd", "Speech-02 HD", "MiniMax", "2025-06", 3, "TTS", "新版高保真", "https://api.minimaxi.com/"},
		{"minimax-voice-clone", "Voice Clone", "MiniMax", "2024-09", 3, "TTS", "音色克隆", "https://api.minimaxi.com/"},
		{"minimax-image-01", "Image-01", "MiniMax", "2024-11", 3, "ImageGen", "图像生成", "https://api.minimaxi.com/"},
		{"minimax-music-01", "Music-01", "MiniMax", "2024-11", 3, "MusicGen", "音乐生成初版", "https://api.minimaxi.com/"},
		{"minimax-embedding-01", "Embedding-01", "MiniMax", "2024-08", 3, "Embedding", "MiniMax 向量", "https://api.minimaxi.com/"},
		{"minimax-rerank-01", "Rerank-01", "MiniMax", "2024-10", 2, "Rerank", "MiniMax Rerank", "https://api.minimaxi.com/"},

		// ========== 9. 讯飞星火 Spark ==========
		{"spark-x1.5", "星火 X1.5", "讯飞", "2026-01", 5, "Reasoning", "X1.5 推理升级版", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"4.0ultra", "星火 4.0 Ultra", "讯飞", "2024-08", 4, "LLM", "4.0 Ultra API 别名", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"generalv3.5", "星火 3.5（通用）", "讯飞", "2024-01", 3, "LLM", "3.5 经典", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"generalv3", "星火 3.0", "讯飞", "2023-10", 2, "LLM", "3.0 经典", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"general", "星火 2.0", "讯飞", "2023-06", 2, "LLM", "2.0 经典", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-pro", "星火 Pro", "讯飞", "2024-06", 3, "LLM", "商用专业", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-lite", "星火 Lite（免费）", "讯飞", "2024-06", 3, "LLM", "免费入门", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-pro-128k", "星火 Pro 128K", "讯飞", "2024-09", 3, "LLM", "Pro 长上下文", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-x1", "星火 X1", "讯飞", "2025-01", 4, "Reasoning", "X1 推理初版", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-x1-lite", "星火 X1 Lite", "讯飞", "2025-03", 3, "Reasoning", "X1 轻量", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-v2.0-vision", "星火图片理解 V2", "讯飞", "2024-07", 3, "VLM", "视觉理解", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-embedding", "星火 Embedding", "讯飞", "2024-06", 3, "Embedding", "讯飞向量", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-embedding-v3", "Spark Embedding V3", "讯飞", "2025-02", 3, "Embedding", "向量 V3", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"iflytek-tts", "讯飞语音合成", "讯飞", "2024-03", 4, "TTS", "超拟人 TTS", "https://www.xfyun.cn/doc/tts/online_tts/API.html"},
		{"iflytek-asr-v2", "讯飞语音识别 V2", "讯飞", "2024-03", 4, "ASR", "中文 ASR SOTA", "https://www.xfyun.cn/doc/asr/voicedictation/API.html"},
		{"iflytek-translation", "讯飞多语翻译", "讯飞", "2024-06", 3, "LLM", "翻译专项", "https://www.xfyun.cn/doc/"},
		{"spark-character", "星火角色扮演", "讯飞", "2024-09", 2, "LLM", "角色对话", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-code", "星火代码", "讯飞", "2024-11", 3, "Code", "代码专项", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-math", "星火数学", "讯飞", "2024-11", 2, "Reasoning", "数学推理", "https://www.xfyun.cn/doc/spark/Web.html"},
		{"spark-image-gen", "星火图像生成", "讯飞", "2025-03", 3, "ImageGen", "讯飞文生图", "https://www.xfyun.cn/doc/spark/Web.html"},

		// ========== 10. 阶跃星辰 StepFun ==========
		{"step-3", "Step-3", "阶跃星辰", "2025-07", 5, "VLM", "Step-3 开源 321B MoE/38B 激活，原生多模态推理", "https://platform.stepfun.com/docs"},
		{"step-3-vlm", "Step-3 VLM", "阶跃星辰", "2025-07", 4, "VLM", "Step-3 视觉版", "https://platform.stepfun.com/docs"},
		{"step-1-8k", "Step-1 8K", "阶跃星辰", "2024-03", 3, "LLM", "Step-1 短版", "https://platform.stepfun.com/docs"},
		{"step-1-32k", "Step-1 32K", "阶跃星辰", "2024-03", 3, "LLM", "Step-1 中版", "https://platform.stepfun.com/docs"},
		{"step-1-128k", "Step-1 128K", "阶跃星辰", "2024-04", 3, "LLM", "Step-1 长版", "https://platform.stepfun.com/docs"},
		{"step-1-256k", "Step-1 256K", "阶跃星辰", "2024-06", 3, "LLM", "Step-1 超长", "https://platform.stepfun.com/docs"},
		{"step-1-flash", "Step-1 Flash", "阶跃星辰", "2024-05", 3, "LLM", "极速版", "https://platform.stepfun.com/docs"},
		{"step-1v-32k", "Step-1V 32K", "阶跃星辰", "2024-04", 3, "VLM", "视觉 32K", "https://platform.stepfun.com/docs"},
		{"step-1.5v-mini", "Step-1.5V Mini", "阶跃星辰", "2024-11", 3, "VLM", "视觉轻量", "https://platform.stepfun.com/docs"},
		{"step-2-16k-exp", "Step-2 Preview", "阶跃星辰", "2024-06", 3, "LLM", "Step-2 预览", "https://platform.stepfun.com/docs"},
		{"step-2-8k", "Step-2 8K", "阶跃星辰", "2024-09", 3, "LLM", "Step-2 短版", "https://platform.stepfun.com/docs"},
		{"step-2-16k-202411", "Step-2 16K 202411", "阶跃星辰", "2024-11", 3, "LLM", "Step-2 快照", "https://platform.stepfun.com/docs"},
		{"step-2x-large", "Step-2X Large", "阶跃星辰", "2025-03", 3, "LLM", "2X 大模型", "https://platform.stepfun.com/docs"},
		{"step-r1-v-mini", "Step-R1-V Mini", "阶跃星辰", "2025-02", 3, "Reasoning", "视觉推理轻量", "https://platform.stepfun.com/docs"},
		{"step-reasoner-mini", "Step Reasoner Mini", "阶跃星辰", "2025-02", 3, "Reasoning", "推理轻量", "https://platform.stepfun.com/docs"},
		{"step-code", "Step Code", "阶跃星辰", "2024-10", 3, "Code", "代码专项", "https://platform.stepfun.com/docs"},
		{"step-tts-mini", "Step TTS Mini", "阶跃星辰", "2024-12", 3, "TTS", "语音合成", "https://platform.stepfun.com/docs"},
		{"step-asr", "Step ASR", "阶跃星辰", "2024-12", 3, "ASR", "语音识别", "https://platform.stepfun.com/docs"},
		{"step-embedding", "Step Embedding", "阶跃星辰", "2024-10", 3, "Embedding", "向量", "https://platform.stepfun.com/docs"},
		{"step-1-pixel", "Step-1 Pixel", "阶跃星辰", "2024-11", 3, "ImageGen", "文生图", "https://platform.stepfun.com/docs"},
		{"step-video-tx", "Step-Video-TX", "阶跃星辰", "2025-02", 3, "VideoGen", "视频生成", "https://platform.stepfun.com/docs"},

		// ========== 11. 零一万物 Yi ==========
		{"yi-lightning", "Yi-Lightning", "零一万物", "2024-10", 4, "LLM", "Lightning 旗舰（极速高性价比）", "https://platform.lingyiwanwu.com/docs"},
		{"yi-lightning-lite", "Yi-Lightning Lite", "零一万物", "2024-10", 3, "LLM", "极速轻量", "https://platform.lingyiwanwu.com/docs"},
		{"yi-large-turbo", "Yi-Large Turbo", "零一万物", "2024-07", 3, "LLM", "Large 加速版", "https://platform.lingyiwanwu.com/docs"},
		{"yi-large-preview", "Yi-Large Preview", "零一万物", "2024-04", 2, "LLM", "Large 预览", "https://platform.lingyiwanwu.com/docs"},
		{"yi-medium", "Yi-Medium", "零一万物", "2024-05", 3, "LLM", "中等商用", "https://platform.lingyiwanwu.com/docs"},
		{"yi-medium-200k", "Yi-Medium 200K", "零一万物", "2024-05", 3, "LLM", "长上下文", "https://platform.lingyiwanwu.com/docs"},
		{"yi-spark", "Yi-Spark", "零一万物", "2024-05", 3, "LLM", "轻量极速", "https://platform.lingyiwanwu.com/docs"},
		{"yi-large-rag", "Yi-Large RAG", "零一万物", "2024-06", 3, "LLM", "RAG 专项", "https://platform.lingyiwanwu.com/docs"},
		{"yi-large-fc", "Yi-Large FC", "零一万物", "2024-07", 3, "LLM", "函数调用", "https://platform.lingyiwanwu.com/docs"},
		{"yi-vision-v2", "Yi-Vision V2", "零一万物", "2025-01", 3, "VLM", "视觉 V2", "https://platform.lingyiwanwu.com/docs"},
		{"yi-vl-34b", "Yi-VL-34B（开源）", "零一万物", "2024-01", 3, "VLM", "开源 34B 视觉", "https://github.com/01-ai/Yi"},
		{"yi-coder-9b-chat", "Yi-Coder 9B", "零一万物", "2024-09", 3, "Code", "代码开源 9B", "https://github.com/01-ai/Yi-Coder"},
		{"yi-coder-1.5b", "Yi-Coder 1.5B", "零一万物", "2024-09", 2, "Code", "代码开源 1.5B", "https://github.com/01-ai/Yi-Coder"},
		{"yi-1.5-34b-chat", "Yi-1.5 34B Chat", "零一万物", "2024-05", 3, "LLM", "1.5 开源 34B", "https://github.com/01-ai/Yi-1.5"},
		{"yi-1.5-9b-chat", "Yi-1.5 9B Chat", "零一万物", "2024-05", 3, "LLM", "1.5 开源 9B", "https://github.com/01-ai/Yi-1.5"},
		{"yi-1.5-6b-chat", "Yi-1.5 6B Chat", "零一万物", "2024-05", 2, "LLM", "1.5 开源 6B", "https://github.com/01-ai/Yi-1.5"},
		{"yi-34b-chat", "Yi 34B Chat", "零一万物", "2023-11", 2, "LLM", "初代 34B", "https://github.com/01-ai/Yi"},
		{"yi-6b-chat", "Yi 6B Chat", "零一万物", "2023-11", 2, "LLM", "初代 6B", "https://github.com/01-ai/Yi"},
		{"yi-embedding", "Yi Embedding", "零一万物", "2024-06", 2, "Embedding", "零一向量", "https://platform.lingyiwanwu.com/docs"},
	}

	sql := "INSERT IGNORE INTO trending_models " +
		"(model_name, display_name, supplier_name, launch_year_month, popularity_stars, model_type, description, source_url, is_active, created_at, updated_at) " +
		"VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, NOW(), NOW())"

	inserted := 0
	for _, r := range rows {
		res := db.Exec(sql, r...)
		if res.Error != nil {
			logger.L.Warn("trending_models insert failed",
				zap.String("model_name", r[0].(string)),
				zap.Error(res.Error),
			)
			continue
		}
		if res.RowsAffected > 0 {
			inserted++
		}
	}

	logger.L.Info("expand trending models migration: complete",
		zap.Int("total_candidates", len(rows)),
		zap.Int("rows_inserted", inserted),
		zap.Int("rows_skipped_existing", len(rows)-inserted),
	)
	return nil
}
